"use client";

import { useState } from "react";
import { usePreviewData } from "@/lib/previewData";
import Artboard from "@/components/Artboard";
import SiteFooter from "@/components/SiteFooter";
import { BoardView } from "@/hooks/useForceGraph";

/**
 * Static preview board — read-only snapshot of the live board served from
 * local JSON files under /preview-data (generated by `npm run export-preview`).
 * No Firebase/Firestore requests happen here. Company bubbles link to the
 * static /preview/company pages, so graduates render from the local JSON too.
 */
export default function PreviewHome() {
  const { nodes, submissions, loading, error } = usePreviewData();
  const [view, setView] = useState<BoardView>("bubble");

  if (loading) {
    return (
      <div className="page-shell flex min-h-screen items-center justify-center">
        <div className="surface-card-soft px-8 py-10 text-center">
          <div className="mx-auto mb-4 h-14 w-14 animate-spin rounded-full border-2 border-cyan-400/30 border-t-cyan-400"></div>
          <p className="text-slate-300">Loading preview data...</p>
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="page-shell flex min-h-screen items-center justify-center p-4">
        <div className="surface-card-soft max-w-md px-8 py-8 text-center">
          <p className="mb-2 text-lg font-semibold text-white">
            Preview data unavailable
          </p>
          <p className="mb-4 text-sm text-slate-400">
            Run <code className="text-cyan-300">npm run export-preview</code>{" "}
            to generate the snapshot under{" "}
            <code className="text-cyan-300">public/preview-data/</code>.
          </p>
          <a href="/" className="primary-btn px-4 py-2">
            Back to Live Board
          </a>
        </div>
      </div>
    );
  }

  const graduateCount = submissions.reduce(
    (sum, row) => sum + (row.company ? 1 : 0),
    0,
  );

  return (
    <main className="page-shell relative overflow-hidden">
      <Artboard nodes={nodes} view={view} companyBaseHref="/preview/company" />

      {/* Title overlay */}
      <div className="fixed top-3 left-3 z-10 rounded-2xl border border-slate-800/70 bg-slate-950/50 px-3 py-2 backdrop-blur sm:top-8 sm:left-8 sm:px-4 sm:py-3">
        <h1 className="mb-0 text-lg font-semibold tracking-tight text-white sm:mb-1 sm:text-4xl">
          CAIE Graduates
        </h1>
        <p className="-mt-1 text-xs italic text-slate-300/90 sm:text-sm tracking-tight">
          Formerly CESS
        </p>
        <p className="text-xs text-slate-400 sm:text-base">
          {nodes.length} {nodes.length === 1 ? "company" : "companies"} •{" "}
          {graduateCount} graduates
        </p>
        <button
          onClick={() => setView((v) => (v === "bubble" ? "grid" : "bubble"))}
          className="mt-3 inline-flex rounded-full border border-slate-700/70 bg-slate-800/80 px-3 py-1.5 text-[11px] font-semibold text-slate-100 shadow-[0_10px_24px_rgba(2,8,23,0.18)] transition-all duration-300 hover:bg-slate-700"
        >
          {view === "bubble" ? "Grid View" : "Bubble View"}
        </button>
      </div>

      {/* Bottom-left credit */}
      <div className="fixed bottom-3 left-3 z-10 select-none sm:bottom-5 sm:left-5">
        <SiteFooter />
      </div>
    </main>
  );
}